version: '3.6'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: '192.168.206.132'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://192.168.206.132'
        registry_external_url 'https://192.168.206.132'
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/registry.example.com.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/registry.example.com.key"
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "postfix"  # Имя сервиса Postfix
        gitlab_rails['smtp_port'] = 25           # Порт Postfix
        gitlab_rails['smtp_domain'] = "192.168.206.132"
        gitlab_rails['smtp_authentication'] = "none"
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['gitlab_email_from'] = "gitlab@192.168.206.132"
        gitlab_rails['gitlab_jira_cloud_integration'] = true
        gitlab_rails['gitlab_openproject_integration'] = true
        # Отключаем встроенные PostgreSQL и Redis
        postgresql['enable'] = false
        redis['enable'] = false
        # Настройка внешнего PostgreSQL
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_host'] = "postgresql"  # Имя сервиса PostgreSQL
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "your_password"
        gitlab_rails['db_database'] = "gitlabhq_production"
        # Настройка внешнего Redis
        gitlab_rails['redis_host'] = "redis"  # Имя сервиса Redis
        gitlab_rails['redis_port'] = "6379"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gitlab/service:/opt/gitlab/service
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/config/ssl:/etc/gitlab/ssl
    networks:
      - gitlab_network

  registry:
    image: registry:2
    container_name: gitlab_registry
    restart: always
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry/data:/var/lib/registry
    networks:
      - gitlab_network

  postgresql:
    image: postgres:14
    container_name: gitlab_postgresql
    restart: always
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: gitlabhq_production
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gitlab_network

  redis:
    image: redis:6
    container_name: gitlab_redis
    restart: always
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - gitlab_network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: gitlab_redisinsight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight_data:/db
    restart: always

  # postfix:
  #   image: marvambass/versatile-postfix:latest
  #   container_name: gitlab_postfix
  #   restart: always
  #   environment:
  #     - MAILNAME=192.168.206.132
  #     - MY_NETWORKS=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
  #     - RELAYHOST=[smtp.gmail.com]:587  # Используем Gmail как релей
  #     - RELAYHOST_PASSWORD=your_gmail_password  # Пароль от Gmail
  #     - RELAYHOST_USERNAME=your_email@gmail.com  # Ваш Gmail
  #     - SMTP_TLS=YES  # Включаем TLS
  #   volumes:
  #     - ./postfix/mails:/var/mail
  #   ports:
  #     - "25:25"  # SMTP-порт
  #   networks:
  #     - gitlab_network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: gitlab_mailhog
    restart: always
    ports:
      - "8025:8025"  # Веб-интерфейс MailHog
      - "1025:1025"  # SMTP-порт
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: bridge