version: '3.6'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: '192.168.206.132'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://192.168.206.132'
        registry_external_url 'https://192.168.206.132'
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/registry.example.com.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/registry.example.com.key"
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "postfix"  # Имя сервиса Postfix
        gitlab_rails['smtp_port'] = 25           # Порт Postfix
        gitlab_rails['smtp_domain'] = "192.168.206.132"
        gitlab_rails['smtp_authentication'] = "none"
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['gitlab_email_from'] = "gitlab@192.168.206.132"
        gitlab_rails['gitlab_jira_cloud_integration'] = true
        gitlab_rails['gitlab_openproject_integration'] = true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gitlab/service:/opt/gitlab/service
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/config/ssl:/etc/gitlab/ssl
    networks:
      - gitlab_network

  registry:
    image: registry:2
    container_name: registry
    restart: always
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    ports:
      - "5000:5000"
    volumes:
      - ./registry/data:/var/lib/registry
    networks:
      - gitlab_network

  postfix:
    image: marvambass/versatile-postfix:latest
    container_name: postfix
    restart: always
    environment:
      - MAILNAME=192.168.206.132
      - MY_NETWORKS=192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
      - RELAYHOST=[smtp.gmail.com]:587  # Используем Gmail как релей
      - RELAYHOST_PASSWORD=your_gmail_password  # Пароль от Gmail
      - RELAYHOST_USERNAME=your_email@gmail.com  # Ваш Gmail
      - SMTP_TLS=YES  # Включаем TLS
    volumes:
      - ./postfix/mails:/var/mail
    ports:
      - "25:25"  # SMTP-порт
    networks:
      - gitlab_network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - "8025:8025"  # Веб-интерфейс MailHog
      - "1025:1025"  # SMTP-порт
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: bridge